config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :enrollments
  resources :batches
  resources :courses
  resources :school_admins
  resources :schools
  resources :classmates
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.erb
<%= link_to 'Schools', schools_path if policy(School).index? %>
<%= link_to 'SchoolAdmins', school_admins_path if policy(SchoolAdmin).index? %>
<%= link_to 'Courses', courses_path if policy(Course).index? %>
<%= link_to 'Batches', batches_path if policy(Batch).index? %>
<%= link_to 'Enrollments', enrollments_path if policy(Enrollment).index? %>
<%= link_to 'Classmates', classmates_path if policy(:classmate).index? %>

<%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>