config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :enrollments
  resources :batches
  resources :courses
  resources :school_admins
  resources :schools
  resources :classmates
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  enum status: { pending: 0, approved: 1, denied: 2 }

  validates :student_id, presence: true
  validates :batch_id, presence: true
  validates :status, presence: true

  belongs_to :student
  belongs_to :batch
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]
  before_action :set_selects, only: %i[ new edit]
  before_action :authorize_user, only: %i[ show edit update destroy ]

  # GET /enrollments or /enrollments.json
  def index
    @enrollments = policy_scope(Enrollment).all
    authorize @enrollments

    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)
    authorize @enrollment

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully created." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @enrollment.destroy!

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    def set_selects
      @statuses = Enrollment.statuses.keys.map { |status| [status.humanize, status] }
      @students = Student.all
      @batches = Batch.all
    end

    def authorize_user
      authorize @enrollment
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:batch_id, :student_id, :status)
    end
end

app/views/enrollments/_enrollment.html.erb
<div id="<%= dom_id enrollment %>">
  Status : <%= enrollment.status %> | <span>Batch: <%= enrollment.batch.name %></span> | <span>Student: <%= enrollment.student.name %></span> | <%= link_to "Show this course", enrollment %>
</div>

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment) do |form| %>
  <% if enrollment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
        <% enrollment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if policy(Enrollment).edit? %>
    <div class="field">
      <%= form.label :status, "Status" %>
      <%= form.select :status, @statuses, {} %>
    </div>

    <div class="field">
      <%= form.label :student_id, "Student" %>
      <%= form.collection_select :student_id, @students, :id, :name, include_blank: true %>
    </div>
  <% end %>

  <% if !policy(Enrollment).edit? %>
    <%= form.hidden_field :status, value: "pending" %>
    <%= form.hidden_field :student_id, value: current_user.id %>
  <% end %>

  <div class="field">
    <%= form.label :batch_id, "Batch" %>
    <%= form.collection_select :batch_id, @batches, :id, :name, include_blank: true %>
  </div>

  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Show this enrollment", @enrollment %> |
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Enrollments</h1>

<div id="enrollments">
  <% @enrollments.each do |enrollment| %>
    <%= render enrollment %>
  <% end %>
</div>

<%= link_to "New enrollment", new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @enrollment %>

<div>
  <%= link_to "Edit this enrollment", edit_enrollment_path(@enrollment) %> |
  <%= link_to "Back to enrollments", enrollments_path %>

  <%= button_to "Destroy this enrollment", @enrollment, method: :delete %>
</div>