config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :enrollments
  resources :batches
  resources :courses
  resources :school_admins
  resources :schools
  resources :classmates
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/school_admin.rb
# frozen_string_literal: true

class SchoolAdmin < User
  has_many :schools, dependent: :destroy
end

app/controllers/school_admins_controller.rb
class SchoolAdminsController < ApplicationController
  before_action :set_school_admin, only: %i[ show edit update destroy ]
  before_action :authorize_user, only: %i[ show edit update destroy ]

  # GET /school_admins or /school_admins.json
  def index
    @school_admins = SchoolAdmin.all
    authorize @school_admins

    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /school_admins/1 or /school_admins/1.json
  def show
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /school_admins/new
  def new
    @school_admin = SchoolAdmin.new
  end

  # GET /school_admins/1/edit
  def edit
  end

  # POST /school_admins or /school_admins.json
  def create
    @school_admin = SchoolAdmin.new(school_admin_params)
    authorize @school_admin

    respond_to do |format|
      if @school_admin.save
        format.html { redirect_to school_admin_url(@school_admin), notice: "School admin was successfully created." }
        format.json { render :show, status: :created, location: @school_admin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @school_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /school_admins/1 or /school_admins/1.json
  def update
    respond_to do |format|
      if @school_admin.update(school_admin_params)
        format.html { redirect_to school_admin_url(@school_admin), notice: "School admin was successfully updated." }
        format.json { render :show, status: :ok, location: @school_admin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @school_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /school_admins/1 or /school_admins/1.json
  def destroy
    @school_admin.destroy!

    respond_to do |format|
      format.html { redirect_to school_admins_url, notice: "School admin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school_admin
      @school_admin = SchoolAdmin.find(params[:id])
    end

    def authorize_user
      authorize @school_admin
    end

    # Only allow a list of trusted parameters through.
    def school_admin_params
      params.require(:school_admin).permit(:first_name, :last_name, :email, :password)
    end
end

app/views/school_admins/_form.html.erb
<%= form_with(model: school_admin) do |form| %>
  <% if school_admin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(school_admin.errors.count, "error") %> prohibited this school_admin from being saved:</h2>

      <ul>
        <% school_admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :school_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :school_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :school_address %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :school_address %>
  </div>

  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/school_admins/_school_admin.html.erb
<div id="<%= dom_id school_admin %>">
  Name: <%= school_admin.name %> | <span>Email: <%= school_admin.email %></span> | <%= link_to "Show this School Admin", school_admin %>
</div>

app/views/school_admins/edit.html.erb
<h1>Editing school admin</h1>

<%= render "form", school_admin: @school_admin %>

<br>

<div>
  <%= link_to "Show this school admin", @school_admin %> |
  <%= link_to "Back to school admins", school_admins_path %>
</div>

app/views/school_admins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>School admins</h1>

<div id="school_admins">
  <% @school_admins.each do |school_admin| %>
    <%= render school_admin %>
  <% end %>
</div>

<%= link_to "New school admin", new_school_admin_path %>

app/views/school_admins/new.html.erb
<h1>New school admin</h1>

<%= render "form", school_admin: @school_admin %>

<br>

<div>
  <%= link_to "Back to school admins", school_admins_path %>
</div>

app/views/school_admins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @school_admin %>

<div>
  <%= link_to "Edit this school admin", edit_school_admin_path(@school_admin) %> |
  <%= link_to "Back to school admins", school_admins_path %>

  <%= button_to "Destroy this school admin", @school_admin, method: :delete %>
</div>