config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :enrollments
  resources :batches
  resources :courses
  resources :school_admins
  resources :schools
  resources :classmates
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/school.rb
# frozen_string_literal: true

class School < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true

  belongs_to :school_admin
  has_many :courses, dependent: :destroy
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: %i[ show edit update destroy ]
  before_action :set_school_admins, only: %i[ new edit]
  before_action :authorize_user, only: %i[ show edit update destroy ]

  # GET /schools or /schools.json
  def index
    @schools = School.all
    authorize @schools

    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /schools/1 or /schools/1.json
  def show
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools or /schools.json
  def create
    @school = School.new(school_params)
    authorize @school

    respond_to do |format|
      if @school.save
        format.html { redirect_to school_url(@school), notice: "School was successfully created." }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1 or /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to school_url(@school), notice: "School was successfully updated." }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1 or /schools/1.json
  def destroy
    @school.destroy!

    respond_to do |format|
      format.html { redirect_to schools_url, notice: "School was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    def set_school_admins
      @school_admins = SchoolAdmin.all
    end

    def authorize_user
      authorize @school
    end

    # Only allow a list of trusted parameters through.
    def school_params
      params.require(:school).permit(:name, :address, :school_admin_id)
    end
end

app/views/schools/_form.html.erb
<%= form_with(model: school) do |form| %>
  <% if school.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
        <% school.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :school_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :school_address %>
  </div>

  <div class="field">
    <%= form.label :school_admin_id, "School Admin" %>
    <%= form.collection_select :school_admin_id, @school_admins, :id, :name, include_blank: true %>
  </div>

  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/_school.html.erb
<div id="<%= dom_id school %>">
  Name: <%= school.name %> | <span>Address: <%= school.address %></span> | <span>School Admin: <%= school.school_admin.name %></span> | <%= link_to "Show this school", school %>
</div>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render "form", school: @school %>

<br>

<div>
  <%= link_to "Show this school", @school %> |
  <%= link_to "Back to schools", schools_path %>
</div>

app/views/schools/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Schools</h1>

<div id="schools">
  <% @schools.each do |school| %>
    <%= render school %>
  <% end %>
</div>

<%= link_to "New school", new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render "form", school: @school %>

<br>

<div>
  <%= link_to "Back to schools", schools_path %>
</div>

app/views/schools/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @school %>

<div>
  <%= link_to "Edit this school", edit_school_path(@school) %> |
  <%= link_to "Back to schools", schools_path %>

  <%= button_to "Destroy this school", @school, method: :delete %>
</div>